security:
  oauth2:
    client:
      # From OIDC app
      clientId: your clientId
      clientSecret: your clientSecret
      # From Authorization Server's metadata
      accessTokenUri: https://dev-460096.oktapreview.com/oauth2/default/v1/token
      userAuthorizationUri: https://dev-460096.oktapreview.com/oauth2/default/v1/authorize
      clientAuthenticationScheme: form
      scope: openid profile email
    resource:
      # from your Auth Server's metadata, check .well-known/openid-configuration if not in .well-known/oauth-authorization-server
      userInfoUri: https://dev-460096.oktapreview.com/oauth2/default/v1/userinfo
